# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  store_var:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: "Store var"
          command: |
            echo $NAME > output.txt
      # - save_cache:
      #     key: v2-prj
      #     paths: 
      #       - output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v2-prj
      - attach_workspace:
          at: ~/
      - run: 
          name: "Print hello"
          command: |
            ls . 
            echo 'hello'
            cat output.txt
            #cat /home/circleci/project/output.txt
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: "Print world"
          command: echo world

workflows:
  default:
    jobs:
      - store_var
      - print_hello
      - print_world:
          requires:
            - print_hello
