defaults: &DAD
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/react 
    
version: 2.1

commands:
  sy:
    parameters:
      to:
        type: string
        default: "crze"
    steps:
      - run : echo << parameters.to >>
jobs:
  store_var:
    <<: *DAD
    steps:
      - checkout
      - sy:
          to: "ZXEA"
      - run: 
          name: "Store var"
          command: |
            echo $NAME > output.txt
      - persist_to_workspace:
          root: ~/react
          paths:
            - output.txt
      # - save_cache:
      #     key: v2-prj
      #     paths:
      #       - ~/output.txt
  print_hello:
    <<: *DAD
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v2-prj
      - attach_workspace:
          at: ~/react
      - run: 
          name: "Print hello"
          command: |
            ls . 
            echo 'hello'
            cat ~/react/output.txt
            #cat /home/circleci/project/output.txt
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # - run: exit 1
      - run: 
          name: "Print world"
          command: echo "world passed"
      - run: 
          name: "Print world"
          command: echo "world failed"
          when: on_fail

workflows:
  default:
    jobs:
      - store_var
      - print_hello:
          requires:
            - store_var
      - print_world:
          requires:
            - print_hello
