- name: "Ansi Install packages"
  become: yes
  yum:
    update_cache: yes
    state: latest

- name: "pull nodejs12 artifacts"
  become: yes
  shell:
    "curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -"
  args:
    chdir: "~/"

- name: "install dependencies"
  become: yes
  yum:
    name: "nodejs"
    state: latest
    update_cache: true

# - name: "Enlist files"
#   become: yes
#   shell: "ls -a {{ role_path }}/files"
#   register: command_output

# - debug: 
#     var: command_output.stdout_lines

- name: "create ~/web"
  ansible.builtin.file:
    path: ~/web
    state: directory
    mode: '0755'

- name: "copy all files"
  become: yes
  copy:
    src: "{{ role_path }}/files"
    dest: ~/web/
    backup: yes

- name: "run app"
  become: yes
  shell:
    "npm start"
  args:
    chdir: ~/web/